spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hello?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
    username: root
    password: Wqs123456
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
